### ISSUE TITLE
Shell commands on macOS

### ISSUE THREAD

**Issue by 90n20** [bitkeks/scs-bootstrap-clusterstacks-openstack#1]
On macOS operating systems the following commands at _create_all.sh_ are a bit different:

### "tr" command does not have the "_--delete_" option.

https://github.com/bitkeks/scs-bootstrap-clusterstacks-openstack/blob/37ad2965d43e38d97bdc2cd9a95480434adae228/create_all.sh#L16

In this case, the comand should be `tr -d`.

### "base64" command does not have the "_-w0_" option.

https://github.com/bitkeks/scs-bootstrap-clusterstacks-openstack/blob/37ad2965d43e38d97bdc2cd9a95480434adae228/create_all.sh#L22

In macOS, line wrapping is disabled by default, so no need to use any argument with the command.

**Comment by bitkeks** [comment]
There's currently no MacOS machine available to test any changes - if you need an update to the script that also works on MacOS (or in your shell/terminal, whichever it is), please open a PR.
